### ISSUE TITLE
 sam_loss:nan

### ISSUE THREAD

**Issue by LRuiRui517** [fangfang11-plog/ADASR#2]
您好，想请教一下您，训练过程中，为什么 sam_loss总是为nan？

**Comment by fangfang11-plog** [comment]
the train log saved https://github.com/fangfang11-plog/ADASR/blob/main/checkpoints/houston18_5_S1%3D0.0008_40000_10000_S2%3D0.0013_200000_20000/log.txt
我在训练过程没有遇到这个问题，或许因为机器不同，你可以尝试修改超参数，如果还不能解决的话可以联系邮箱l.h.fang228@gmail.com，欢迎交流
