### ISSUE TITLE
Chikusei dataset

### ISSUE THREAD

**Issue by LRuiRui517** [fangfang11-plog/ADASR#3]
Hello, I converted Chikusei data set to image format, may I ask if there is only one image in Chikusei data set?

**Comment by LRuiRui517** [comment]
In addition, I would like to ask how the spectral response matrix corresponding to the data used in the article is calculated.

**Comment by fangfang11-plog** [comment]
ye, only one image in Chikusei data set. we adopt unsupervised learning.

> Hello, I converted Chikusei data set to image format, may I ask if there is only one image in Chikusei data set?



> Hello, I converted Chikusei data set to image format, may I ask if there is only one image in Chikusei data set?

**Comment by LRuiRui517** [comment]
好的 感谢
